name: Deploy Hello World Node.js App

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: navsho/hello-world-nodejs
  DOCKER_IMAGE_TAG: latest
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: navsho
          password: ${{ secrets.DOCKER_HUB_TOKEN }} # Ensure this is set in GitHub Secrets

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

      - name: Set up Kubernetes configuration
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" | base64 --decode > ~/.kube/config

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform Deployment
        run: terraform plan -out=tfplan

      - name: Deploy to Kubernetes
        run: terraform apply -auto-approve tfplan

    